// src/pages/Profile.jsx
import React, { useState, useEffect } from "react";
import { User } from "../api/entities";
import { GearItem } from "../api/entities";
import { Rental } from "../api/entities";
import { UploadFile } from "../api/integrations";
import TaxInformationForm from "../components/TaxInformationForm";
import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { Textarea } from "../components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { Badge } from "../components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../components/ui/tabs";
import { Label } from "../components/ui/label";
import { 
  User as UserIcon, 
  MapPin, 
  Phone, 
  Calendar, 
  Star, 
  Shield, 
  Camera,
  Edit,
  Save,
  Settings,
  Tent,
  Mountain,
  MessageCircle,
  FileText
} from "lucide-react";
import { format } from "date-fns";
import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { createPageUrl } from "../utils";

function ReviewCard({ review }) {
  return (
    <div className="border border-gray-200 p-4 rounded-xl">
      <div className="flex items-start gap-3">
        <div className="w-10 h-10 bg-gray-100 rounded-full flex items-center justify-center">
          <MessageCircle className="w-5 h-5 text-gray-500" />
        </div>
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="font-semibold">{review.reviewer_name}</span>
            <div className="flex">
              {[...Array(5)].map((_, i) => (
                <Star key={i} className={`w-4 h-4 ${i < review.rating ? 'text-yellow-400 fill-current' : 'text-gray-300'}`} />
              ))}
            </div>
          </div>
          <p className="text-sm text-gray-600">{review.review}</p>
        </div>
      </div>
    </div>
  );
}

export default function Profile() {
  const [user, setUser] = useState(null);
  const [myGear, setMyGear] = useState([]);
  const [myRentals, setMyRentals] = useState([]);
  const [reviews, setReviews] = useState([]); 
  const [isLoading, setIsLoading] = useState(true);
  const [isEditing, setIsEditing] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isUploadingPhoto, setIsUploadingPhoto] = useState(false);
  const [profileData, setProfileData] = useState({
    bio: "",
    location: "",
    phone: "",
    profile_image: ""
  });

  useEffect(() => {
    loadProfileData();
  }, []);

  const loadProfileData = async () => {
    try {
      setIsLoading(true);
      const [currentUser, allGear, allRentals, allUsers] = await Promise.all([ 
        User.me(),
        GearItem.list(),
        Rental.list(),
        User.list() 
      ]);

      const userMap = new Map(allUsers.map(u => [u.email, u.full_name])); 

      const userGear = allGear.filter(item => item.created_by === currentUser.email);
      const userRentals = allRentals.filter(rental => 
        rental.renter_email === currentUser.email || rental.owner_email === currentUser.email
      );

      const userReviews = allRentals
        .filter(r => (r.owner_email === currentUser.email && r.renter_review) || (r.renter_email === currentUser.email && r.owner_review))
        .map(r => {
          const isOwnerReview = r.owner_email === currentUser.email && r.renter_review;
          return {
            reviewer_name: userMap.get(isOwnerReview ? r.renter_email : r.owner_email) || 'A User',
            rating: isOwnerReview ? r.renter_rating : r.owner_rating,
            review: isOwnerReview ? r.renter_review : r.owner_review,
          };
        }).filter(Boolean);

      setUser(currentUser);
      setMyGear(userGear);
      setMyRentals(userRentals);
      setReviews(userReviews); 
      setProfileData({
        bio: currentUser.bio || "",
        location: currentUser.location || "",
        phone: currentUser.phone || "",
        profile_image: currentUser.profile_image || ""
      });
    } catch (error) {
      console.error("Error loading profile:", error);
      User.login();
    } finally {
      setIsLoading(false);
    }
  };

  const handlePhotoUpload = async (e) => {
    const file = e.target.files[0];
    if (!file) return;

    setIsUploadingPhoto(true);
    try {
      const { file_url } = await UploadFile({ file });
      setProfileData(prev => ({ ...prev, profile_image: file_url }));
    } catch (error) {
      console.error("Error uploading photo:", error);
    }
    setIsUploadingPhoto(false);
  };

  const handleSaveProfile = async () => {
    setIsSaving(true);
    try {
      await User.updateMyUserData(profileData);
      setUser(prev => ({ ...prev, ...profileData }));
      setIsEditing(false);
    } catch (error) {
      console.error("Error saving profile:", error);
    }
    setIsSaving(false);
  };

  const handleRequestVerification = async () => { 
    try {
      await User.updateMyUserData({ verification_status: 'pending' });
      loadProfileData(); // Reload data to show updated status
    } catch (error) {
      console.error("Error requesting verification:", error);
    }
  };

  const getVerificationBadge = () => {
    const status = user?.verification_status || "unverified";
    const colors = {
      verified: "bg-green-100 text-green-800 border-green-200",
      pending: "bg-yellow-100 text-yellow-800 border-yellow-200",
      unverified: "bg-gray-100 text-gray-800 border-gray-200"
    };
    
    return (
      <Badge className={`${colors[status]} border`}>
        <Shield className="w-3 h-3 mr-1" />
        {status === "verified" ? "Verified" : status === "pending" ? "Pending" : "Unverified"}
      </Badge>
    );
  };

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-green-50 p-4 md:p-8">
        <div className="max-w-6xl mx-auto animate-pulse">
          <div className="h-8 bg-gray-200 rounded mb-6 w-48"></div>
          <div className="grid lg:grid-cols-3 gap-8">
            <div className="space-y-4">
              <div className="h-64 bg-gray-200 rounded-xl"></div>
              <div className="h-32 bg-gray-200 rounded-xl"></div>
            </div>
            <div className="lg:col-span-2 h-96 bg-gray-200 rounded-xl"></div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-green-50 p-4 md:p-8">
      <div className="max-w-6xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-8"
        >
          <div className="flex justify-between items-center">
            <h1 className="text-3xl font-bold text-gray-900">My Profile</h1>
            {user?.role === 'admin' && (
              <Link to={createPageUrl("AdminConsole")}>
                <Button className="bg-red-600 hover:bg-red-700">
                  <Settings className="w-4 h-4 mr-2" />
                  Admin Console
                </Button>
              </Link>
            )}
          </div>
        </motion.div>

        <div className="grid lg:grid-cols-3 gap-8">
          {/* Profile Card */}
          <div className="space-y-6">
            <Card className="bg-white/80 backdrop-blur-sm shadow-lg border-gray-100">
              <CardHeader className="text-center pb-6">
                <div className="relative mx-auto mb-4">
                  <div className="w-32 h-32 rounded-full overflow-hidden bg-gray-100 border-4 border-white shadow-lg">
                    {profileData.profile_image ? (
                      <img
                        src={profileData.profile_image}
                        alt={user?.full_name}
                        className="w-full h-full object-cover"
                      />
                    ) : (
                      <div className="w-full h-full flex items-center justify-center bg-emerald-100">
                        <UserIcon className="w-16 h-16 text-emerald-600" />
                      </div>
                    )}
                  </div>
                  {isEditing && (
                    <label className="absolute bottom-0 right-0 p-2 bg-emerald-600 text-white rounded-full cursor-pointer hover:bg-emerald-700 shadow-lg">
                      <Camera className="w-4 h-4" />
                      <input
                        type="file"
                        accept="image/*"
                        onChange={handlePhotoUpload}
                        className="hidden"
                        disabled={isUploadingPhoto}
                      />
                    </label>
                  )}
                </div>
                
                <div>
                  <h2 className="text-2xl font-bold text-gray-900 mb-2">{user?.full_name}</h2>
                  <p className="text-gray-600 mb-3">{user?.email}</p>
                  {getVerificationBadge()}
                </div>
              </CardHeader>
              
              <CardContent className="space-y-4">
                {isEditing ? (
                  <div className="space-y-4">
                    <div>
                      <Label htmlFor="bio">Bio</Label>
                      <Textarea
                        id="bio"
                        value={profileData.bio}
                        onChange={(e) => setProfileData(prev => ({ ...prev, bio: e.target.value }))}
                        placeholder="Tell us about yourself..."
                        className="h-24"
                      />
                    </div>
                    <div>
                      <Label htmlFor="location">Location</Label>
                      <Input
                        id="location"
                        value={profileData.location}
                        onChange={(e) => setProfileData(prev => ({ ...prev, location: e.target.value }))}
                        placeholder="City, State"
                      />
                    </div>
                    <div>
                      <Label htmlFor="phone">Phone</Label>
                      <Input
                        id="phone"
                        value={profileData.phone}
                        onChange={(e) => setProfileData(prev => ({ ...prev, phone: e.target.value }))}
                        placeholder="(555) 123-4567"
                      />
                    </div>
                    <div className="flex gap-2">
                      <Button
                        onClick={handleSaveProfile}
                        disabled={isSaving}
                        className="flex-1 bg-emerald-600 hover:bg-emerald-700"
                      >
                        <Save className="w-4 h-4 mr-2" />
                        {isSaving ? "Saving..." : "Save"}
                      </Button>
                      <Button
                        onClick={() => setIsEditing(false)}
                        variant="outline"
                        className="flex-1"
                      >
                        Cancel
                      </Button>
                    </div>
                  </div>
                ) : (
                  <div className="space-y-4">
                    {user?.bio && (
                      <div>
                        <h4 className="font-semibold text-gray-900 mb-2">About</h4>
                        <p className="text-gray-600 text-sm leading-relaxed">{user.bio}</p>
                      </div>
                    )}
                    {user?.location && (
                      <div className="flex items-center gap-2 text-gray-600">
                        <MapPin className="w-4 h-4" />
                        <span className="text-sm">{user.location}</span>
                      </div>
                    )}
                    {user?.phone && (
                      <div className="flex items-center gap-2 text-gray-600">
                        <Phone className="w-4 h-4" />
                        <span className="text-sm">{user.phone}</span>
                      </div>
                    )}
                    <div className="flex items-center gap-2 text-gray-600">
                      <Calendar className="w-4 h-4" />
                      <span className="text-sm">
                        Joined {user?.created_date ? format(new Date(user.created_date), "MMMM yyyy") : "Recently"}
                      </span>
                    </div>
                    {user?.verification_status === 'unverified' && ( 
                      <Button onClick={handleRequestVerification} variant="secondary" className="w-full">
                        <Shield className="w-4 h-4 mr-2" />
                        Request Verification
                      </Button>
                    )}
                    <Button
                      onClick={() => setIsEditing(true)}
                      variant="outline"
                      className="w-full"
                    >
                      <Edit className="w-4 h-4 mr-2" />
                      Edit Profile
                    </Button>
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Stats Card */}
            <Card className="bg-white/80 backdrop-blur-sm shadow-lg border-gray-100">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Star className="w-5 h-5 text-yellow-500" />
                  Stats
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="flex justify-between items-center">
                  <span className="text-gray-600">Trust Score</span>
                  <div className="flex items-center gap-1">
                    <Star className="w-4 h-4 text-yellow-500 fill-current" />
                    <span className="font-semibold">{user?.trust_score || 5.0}</span>
                  </div>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-gray-600">Total Rentals</span>
                  <span className="font-semibold">{myRentals.length}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-gray-600">Listed Gear</span>
                  <span className="font-semibold">{myGear.length}</span>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Main Content */}
          <div className="lg:col-span-2">
            <Tabs defaultValue="reviews" className="space-y-6"> 
              <TabsList className="bg-white shadow-sm border border-gray-100">
                <TabsTrigger value="reviews">Reviews ({reviews.length})</TabsTrigger>
                <TabsTrigger value="gear" className="px-6">My Gear ({myGear.length})</TabsTrigger>
                <TabsTrigger value="rentals" className="px-6">Rental History ({myRentals.length})</TabsTrigger>
                <TabsTrigger value="tax-info" className="px-6">
                  <FileText className="w-4 h-4 mr-2" />
                  Tax Information
                </TabsTrigger>
              </TabsList>

              <TabsContent value="reviews"> 
                <Card className="bg-white/80 backdrop-blur-sm shadow-lg border-gray-100">
                  <CardHeader>
                    <CardTitle>Reviews</CardTitle>
                  </CardHeader>
                  <CardContent>
                    {reviews.length > 0 ? (
                      <div className="space-y-4">
                        {reviews.map((review, index) => (
                          <ReviewCard key={index} review={review} />
                        ))}
                      </div>
                    ) : (
                      <div className="text-center py-12">
                        <MessageCircle className="w-16 h-16 text-gray-300 mx-auto mb-4" />
                        <h3 className="text-lg font-semibold text-gray-700">No reviews yet</h3>
                        <p className="text-gray-500">Complete rentals to get reviews.</p>
                      </div>
                    )}
                  </CardContent>
                </Card>
              </TabsContent>

              <TabsContent value="gear">
                <Card className="bg-white/80 backdrop-blur-sm shadow-lg border-gray-100">
                  <CardHeader className="flex flex-row items-center justify-between">
                    <CardTitle className="flex items-center gap-2">
                      <Tent className="w-5 h-5" />
                      My Listed Gear ({myGear.length})
                    </CardTitle>
                    <Link to={createPageUrl("ListGear")}>
                      <Button className="bg-emerald-600 hover:bg-emerald-700">
                        List New Gear
                      </Button>
                    </Link>
                  </CardHeader>
                  <CardContent>
                    {myGear.length > 0 ? (
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        {myGear.map((item) => (
                          <motion.div
                            key={item.id}
                            whileHover={{ scale: 1.02 }}
                            className="border border-gray-200 rounded-xl p-4 hover:shadow-md transition-all"
                          >
                            <div className="flex items-start gap-3">
                              <div className="w-16 h-16 bg-gray-100 rounded-lg overflow-hidden">
                                {item.photos && item.photos.length > 0 ? (
                                  <img
                                    src={item.photos[0]}
                                    alt={item.title}
                                    className="w-full h-full object-cover"
                                  />
                                ) : (
                                  <div className="w-full h-full flex items-center justify-center">
                                    <Mountain className="w-8 h-8 text-gray-400" />
                                  </div>
                                )}
                              </div>
                              <div className="flex-1">
                                <h4 className="font-semibold text-gray-900 mb-1">{item.title}</h4>
                                <p className="text-sm text-gray-600 mb-2 line-clamp-2">{item.description}</p>
                                <div className="flex justify-between items-center">
                                  <span className="text-emerald-600 font-bold">${item.daily_rate}/day</span>
                                  <Badge variant={item.availability ? "default" : "secondary"}>
                                    {item.availability ? "Available" : "Unavailable"}
                                  </Badge>
                                </div>
                              </div>
                            </div>
                          </motion.div>
                        ))}
                      </div>
                    ) : (
                      <div className="text-center py-12">
                        <Tent className="w-16 h-16 text-gray-300 mx-auto mb-4" />
                        <h3 className="text-lg font-semibold text-gray-700 mb-2">No gear listed yet</h3>
                        <p className="text-gray-500 mb-4">Start earning by listing your outdoor gear</p>
                        <Link to={createPageUrl("ListGear")}>
                          <Button className="bg-emerald-600 hover:bg-emerald-700">
                            List Your First Item
                          </Button>
                        </Link>
                      </div>
                    )}
                  </CardContent>
                </Card>
              </TabsContent>

              <TabsContent value="rentals">
                <Card className="bg-white/80 backdrop-blur-sm shadow-lg border-gray-100">
                  <CardHeader>
                    <CardTitle>Rental History ({myRentals.length})</CardTitle>
                  </CardHeader>
                  <CardContent>
                    {myRentals.length > 0 ? (
                      <div className="space-y-4">
                        {myRentals.slice(0, 10).map((rental) => (
                          <div key={rental.id} className="border border-gray-200 rounded-xl p-4">
                            <div className="flex justify-between items-start mb-2">
                              <div>
                                <p className="font-semibold text-gray-900">
                                  {rental.renter_email === user?.email ? "Rented" : "Lent"} Gear
                                </p>
                                <p className="text-sm text-gray-600">
                                  {rental.start_date && rental.end_date ?
                                    `${format(new Date(rental.start_date), "MMM d")} - ${format(new Date(rental.end_date), "MMM d, yyyy")}` :
                                    "Date TBD"
                                  }
                                </p>
                              </div>
                              <Badge className={
                                rental.status === 'completed' ? 'bg-green-100 text-green-800' :
                                rental.status === 'active' ? 'bg-blue-100 text-blue-800' :
                                rental.status === 'confirmed' ? 'bg-yellow-100 text-yellow-800' :
                                'bg-gray-100 text-gray-800'
                              }>
                                {rental.status}
                              </Badge>
                            </div>
                            <p className="text-sm text-gray-600">${rental.total_amount} total</p>
                          </div>
                        ))}
                      </div>
                    ) : (
                      <div className="text-center py-12">
                        <Calendar className="w-16 h-16 text-gray-300 mx-auto mb-4" />
                        <h3 className="text-lg font-semibold text-gray-700 mb-2">No rental history</h3>
                        <p className="text-gray-500">Start by renting or listing gear</p>
                      </div>
                    )}
                  </CardContent>
                </Card>
              </TabsContent>

              <TabsContent value="tax-info">
                <TaxInformationForm
                  user={user}
                  onUpdate={(updatedTaxInfo) => {
                    setUser(prev => ({ ...prev, ...updatedTaxInfo }));
                  }}
                />
              </TabsContent>
            </Tabs>
          </div>
        </div>
      </div>
    </div>
  );
}

// src/routes/profile/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { User, GearItem } from '$lib/api/entities.js';
	import { Button } from '$lib/components/ui/button';
	import { Input } from '$lib/components/ui/input';
	import { Card, CardContent, CardHeader, CardTitle } from '$lib/components/ui/card';
	import { Badge } from '$lib/components/ui/badge';
	import { Tabs, TabsContent, TabsList, TabsTrigger } from '$lib/components/ui/tabs';
	import { User as UserIcon, Mail, MapPin, Calendar, Settings, Star, Package } from 'lucide-svelte';

	let user: any = null;
	let userGear: any[] = [];
	let loading = true;
	let editMode = false;
	let editData = {
		name: '',
		email: '',
		location: ''
	};

	onMount(async () => {
		try {
			user = await User.me();
			if (user) {
				editData = {
					name: user.name || '',
					email: user.email || '',
					location: user.location || ''
				};

				// Load user's gear
				const allGear = await GearItem.list();
				userGear = allGear.filter((item: any) => item.ownerId === user.id);
			}
		} catch (error) {
			console.error('Error loading profile:', error);
		} finally {
			loading = false;
		}
	});

	async function saveProfile() {
		if (!user) return;

		try {
			await User.updateMe(editData);
			user = { ...user, ...editData };
			editMode = false;
		} catch (error) {
			console.error('Error updating profile:', error);
		}
	}

	function formatDate(dateString: string) {
		return new Date(dateString).toLocaleDateString();
	}
</script>

<div class="min-h-screen bg-gradient-to-br from-slate-50 via-white to-green-50 p-4 md:p-8">
	<div class="max-w-6xl mx-auto">
		{#if loading}
			<div class="animate-pulse">
				<div class="h-8 bg-gray-200 rounded w-1/4 mb-8"></div>
				<div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
					<div class="lg:col-span-1">
						<div class="bg-gray-200 rounded-xl h-64"></div>
					</div>
					<div class="lg:col-span-2">
						<div class="bg-gray-200 rounded-xl h-64"></div>
					</div>
				</div>
			</div>
		{:else if !user}
			<Card class="bg-white/80 backdrop-blur-sm shadow-lg">
				<CardContent class="p-8 text-center">
					<UserIcon class="w-16 h-16 text-gray-300 mx-auto mb-4" />
					<h2 class="text-xl font-semibold text-gray-600 mb-4">Sign In Required</h2>
					<p class="text-gray-500 mb-6">You need to be signed in to view your profile</p>
					<Button class="bg-emerald-600 hover:bg-emerald-700">
						Sign In
					</Button>
				</CardContent>
			</Card>
		{:else}
			<div class="mb-8">
				<h1 class="text-3xl font-bold text-gray-900 mb-2">Profile</h1>
				<p class="text-gray-600">Manage your account and gear listings</p>
			</div>

			<div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
				<!-- Profile Info -->
				<div class="lg:col-span-1">
					<Card class="bg-white/80 backdrop-blur-sm shadow-lg">
						<CardHeader class="text-center">
							<div class="w-24 h-24 bg-emerald-100 rounded-full flex items-center justify-center mx-auto mb-4">
								<span class="text-3xl font-bold text-emerald-700">
									{user.name?.charAt(0) || 'U'}
								</span>
							</div>
							<CardTitle class="text-xl">{user.name || 'User'}</CardTitle>
							<div class="flex items-center justify-center gap-1 text-yellow-500">
								<Star class="w-4 h-4 fill-current" />
								<span class="text-sm font-medium text-gray-700">
									{user.rating || '5.0'} ({user.reviewCount || '0'} reviews)
								</span>
							</div>
						</CardHeader>
						<CardContent class="space-y-4">
							{#if editMode}
								<div class="space-y-3">
									<div>
										<label for="edit-name" class="block text-sm font-medium text-gray-700 mb-1">Name</label>
										<Input id="edit-name" bind:value={editData.name} class="bg-white border-gray-200" />
									</div>
									<div>
										<label for="edit-email" class="block text-sm font-medium text-gray-700 mb-1">Email</label>
										<Input id="edit-email" bind:value={editData.email} type="email" class="bg-white border-gray-200" />
									</div>
									<div>
										<label for="edit-location" class="block text-sm font-medium text-gray-700 mb-1">Location</label>
										<Input id="edit-location" bind:value={editData.location} class="bg-white border-gray-200" />
									</div>
									<div class="flex gap-2">
										<Button on:click={saveProfile} size="sm" class="bg-emerald-600 hover:bg-emerald-700">
											Save
										</Button>
										<Button on:click={() => editMode = false} size="sm" variant="outline">
											Cancel
										</Button>
									</div>
								</div>
							{:else}
								<div class="space-y-3">
									<div class="flex items-center gap-2 text-gray-600">
										<Mail class="w-4 h-4" />
										<span class="text-sm">{user.email || 'No email'}</span>
									</div>
									{#if user.location}
										<div class="flex items-center gap-2 text-gray-600">
											<MapPin class="w-4 h-4" />
											<span class="text-sm">{user.location}</span>
										</div>
									{/if}
									{#if user.createdAt}
										<div class="flex items-center gap-2 text-gray-600">
											<Calendar class="w-4 h-4" />
											<span class="text-sm">Joined {formatDate(user.createdAt)}</span>
										</div>
									{/if}
								</div>
								<Button on:click={() => editMode = true} variant="outline" class="w-full">
									<Settings class="w-4 h-4 mr-2" />
									Edit Profile
								</Button>
							{/if}
						</CardContent>
					</Card>
				</div>

				<!-- Profile Content -->
				<div class="lg:col-span-2">
					<Tabs value="gear" class="space-y-6">
						<TabsList class="bg-white shadow-sm border border-gray-100">
							<TabsTrigger value="gear" class="px-6">My Gear ({userGear.length})</TabsTrigger>
							<TabsTrigger value="reviews" class="px-6">Reviews</TabsTrigger>
							<TabsTrigger value="settings" class="px-6">Settings</TabsTrigger>
						</TabsList>

						<TabsContent value="gear" class="space-y-4">
							{#if userGear.length === 0}
								<Card class="bg-white/80 backdrop-blur-sm shadow-lg">
									<CardContent class="p-8 text-center">
										<Package class="w-16 h-16 text-gray-300 mx-auto mb-4" />
										<h3 class="text-xl font-semibold text-gray-600 mb-2">No gear listed yet</h3>
										<p class="text-gray-500 mb-6">Start earning by listing your outdoor equipment</p>
										<Button class="bg-emerald-600 hover:bg-emerald-700">
											List Your First Item
										</Button>
									</CardContent>
								</Card>
							{:else}
								<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
									{#each userGear as item}
										<Card class="bg-white/80 backdrop-blur-sm shadow-lg hover:shadow-xl transition-all duration-300">
											<CardContent class="p-4">
												<div class="aspect-[4/3] bg-gradient-to-br from-gray-100 to-gray-200 rounded-lg mb-4 overflow-hidden">
													{#if item.photos && item.photos.length > 0}
														<img 
															src={item.photos[0]} 
															alt={item.name}
															class="w-full h-full object-cover"
														/>
													{:else}
														<div class="w-full h-full flex items-center justify-center">
															<Package class="w-12 h-12 text-gray-400" />
														</div>
													{/if}
												</div>
												<h3 class="font-semibold text-gray-900 mb-2">{item.name}</h3>
												<div class="flex items-center justify-between">
													<Badge variant="secondary">{item.category}</Badge>
													<span class="font-bold text-emerald-600">
														${item.pricePerDay}/day
													</span>
												</div>
											</CardContent>
										</Card>
									{/each}
								</div>
							{/if}
						</TabsContent>

						<TabsContent value="reviews">
							<Card class="bg-white/80 backdrop-blur-sm shadow-lg">
								<CardContent class="p-8 text-center">
									<Star class="w-16 h-16 text-gray-300 mx-auto mb-4" />
									<h3 class="text-xl font-semibold text-gray-600 mb-2">No reviews yet</h3>
									<p class="text-gray-500">Reviews from renters will appear here</p>
								</CardContent>
							</Card>
						</TabsContent>

						<TabsContent value="settings">
							<Card class="bg-white/80 backdrop-blur-sm shadow-lg">
								<CardHeader>
									<CardTitle>Account Settings</CardTitle>
								</CardHeader>
								<CardContent class="space-y-4">
									<div class="flex items-center justify-between p-4 bg-gray-50 rounded-lg">
										<div>
											<h4 class="font-medium text-gray-900">Email Notifications</h4>
											<p class="text-sm text-gray-600">Receive updates about your rentals</p>
										</div>
										<Button variant="outline" size="sm">
											Configure
										</Button>
									</div>
									<div class="flex items-center justify-between p-4 bg-gray-50 rounded-lg">
										<div>
											<h4 class="font-medium text-gray-900">Privacy Settings</h4>
											<p class="text-sm text-gray-600">Control who can see your profile</p>
										</div>
										<Button variant="outline" size="sm">
											Manage
										</Button>
									</div>
									<div class="flex items-center justify-between p-4 bg-red-50 rounded-lg">
										<div>
											<h4 class="font-medium text-red-900">Delete Account</h4>
											<p class="text-sm text-red-600">Permanently delete your account and data</p>
										</div>
										<Button variant="destructive" size="sm">
											Delete
										</Button>
									</div>
								</CardContent>
							</Card>
						</TabsContent>
					</Tabs>
				</div>
			</div>
		{/if}
	</div>
</div>
